[package]
name = "booksearch"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = "0.12.7"
scraper = "0.21.0"
serde_json = "1.0.133"
tokio = { version = "1.40.0", features = ["rt", "rt-multi-thread", "macros"] }
toml = "0.8.19"
serde = { version = "1.0.210", features = ["derive"] }
